### 복습 (데이터프레임)
1. 민원(콜센터) 질의응답_다산콜센터_일반행정 문의_Training.json 파일을 로드
2. 고객질문(요청), 상담사답변 컬럼의 문자 정규화 (특수문자 제거, 공백제거)
3. 고객질문에 대한 즉각적인 상담사의 답변이 있는 행들만 남기고 나머지는 제거
4. 고객의 질문과 상담사의 답변을 하나의 행으로 결합
5. 인덱스를 초기화하고 label 컬럼을 생성하여 1을 대입

In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_json("data/민원(콜센터) 질의응답_다산콜센터_일반행정 문의_Training.json")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50336 entries, 0 to 50335
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   도메인        50336 non-null  object
 1   카테고리       50336 non-null  object
 2   대화셋일련번호    50336 non-null  object
 3   화자         50336 non-null  object
 4   문장번호       50336 non-null  int64
 5   고객의도       50336 non-null  object
 6   상담사의도      50336 non-null  object
 7   QA         50336 non-null  object
 8   고객질문(요청)   50336 non-null  object
 9   상담사질문(요청)  50336 non-null  object
 10  고객답변       50336 non-null  object
 11  상담사답변      50336 non-null  object
 12  개체명        50336 non-null  object
 13  용어사전       50336 non-null  object
 14  지식베이스      50336 non-null  object
dtypes: int64(1), object(14)
memory usage: 5.8+ MB

In [4]:
# 컬럼의 이름에서 좌우의 공백을 제거 (strip() -> str 내장함수)
df.columns.map( lambda x : x.strip() )
# [x.strip() for x in df.columns] <- 이것도 같은 기능

Index(['도메인', '카테고리', '대화셋일련번호', '화자', '문장번호', '고객의도', '상담사의도', 'QA',
       '고객질문(요청)', '상담사질문(요청)', '고객답변', '상담사답변', '개체명', '용어사전', '지식베이스'],
      dtype='object')

In [5]:
# 정규화
def normalize_token_text(text : str) -> str:
    text = re.sub(r'[^가-힣a-zA-Z0-9\s\.]', " ", text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
df['고객질문(요청)'] = df['고객질문(요청)'].map(normalize_token_text)
df['상담사답변'] = df['상담사답변'].map(normalize_token_text)

In [6]:
df.head()

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
0,다산콜센터,일반행정 문의,B2240,고객,1,지방세납부,,Q,지방세를 내려면 어떻게 해야됩니까,,,,지방세,지방세/세금,"지방세,세금"
1,다산콜센터,일반행정 문의,B2240,상담사,2,,지방세납부,A,,,,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.,"은행, 사이트, 지방세, 납부",은행/공공기관/ 지방세/세금,"사이트,세금"
2,다산콜센터,일반행정 문의,B2240,고객,3,지방세납부,,Q,은행 어플에서도 됩니까,,,,"은행, 어플",은행/공공기관,"어플,공공기관"
3,다산콜센터,일반행정 문의,B2240,상담사,4,,지방세납부,Q,,어떤 은행을 이용하고 계십니까?,,,은행,은행/공공기관,"은행,공공기관"
4,다산콜센터,일반행정 문의,B2240,고객,5,지방세납부,,A,,,기업은행을 이용하고 있습니다.,,기업은행,기업은행/상호,"기업은행,상호"

In [7]:
# 고객질문-답변 행 남기고 나머지 제거

# 1번 조건식 -> 현재 행에서 고객질문(요청) 데이터가 ''가 아니고 다음행의 상담사답변의 value가 ''이 아닌 경우
flag1 = (df['고객질문(요청)'] != '') & (df['상담사답변'].shift(-1) != '')
# 2번 조건식 -> 현재 행에서 상담사 답변이 ''가 아니고 전 행의 고객질문 데이터가 ''가 아닌 경우
flag2 = (df['상담사답변'] != '') & (df['고객질문(요청)'] != '' )


# 질문-답변의 인덱스 맞추기
df['상담사답변'] = df['상담사답변'].shift(-1)

# 고객질문 데이터에서 ''가 아닌 데이터만 필터
df = df.loc[
    df['고객질문(요청)'] != ''
]
df.drop_duplicates('고객질문(요청)')

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
0,다산콜센터,일반행정 문의,B2240,고객,1,지방세납부,,Q,지방세를 내려면 어떻게 해야됩니까,,,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.,지방세,지방세/세금,"지방세,세금"
2,다산콜센터,일반행정 문의,B2240,고객,3,지방세납부,,Q,은행 어플에서도 됩니까,,,,"은행, 어플",은행/공공기관,"어플,공공기관"
6,다산콜센터,일반행정 문의,B2240,고객,7,지방세납부,,Q,은행을 직접방문해도 됩니까,,,방문납부도 가능합니다.,은행,은행/공공기관,"은행,공공기관"
8,다산콜센터,일반행정 문의,B2240,고객,9,지방세납부,,Q,은행위치 좀 알 수 있습니까,,,,은행,은행/공공기관,"은행,공공기관"
12,다산콜센터,일반행정 문의,B2240,고객,13,지방세납부,,Q,버스로 가는 방법도 있습니까,,,도보로 가시는게 빠를 것 같습니다.,버스,버스/교통수단,"버스,교통수단"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50324,다산콜센터,일반행정 문의,B35809,고객,9,여성전용아파트,,Q,꼭 서울시에 근무해야하나요,,,서울소재 직장근무로 제한하고있습니다.,"서울시, 근무","서울시/서울/서울특별시, 근무",근무
50326,다산콜센터,일반행정 문의,B35809,고객,11,여성전용아파트,,Q,임대료는 어떻게 되나요,,,62400원 입니다.,임대료,"임대료, 월세","임대료,월세"
50328,다산콜센터,일반행정 문의,B35809,고객,13,여성전용아파트,,Q,보증금도 있나요,,,1423200원 입니다.,보증금,보증금/예치금,"보증금,예치금"
50332,다산콜센터,일반행정 문의,B35809,고객,17,여성전용아파트,,Q,입주순위도 있나요,,,1 3순위가 있습니다.,"입주, 순위","입주/이사, 순위/순서","순위,순서"
50334,다산콜센터,일반행정 문의,B35809,고객,19,여성전용아파트,,Q,1순위는 누가 되나요,,,국가유공자 자녀 및 국민기초생활수급권자를 1순위로 두고있습니다.,순위,순위/순서,"순위,순서"

In [8]:
# 인덱스 초기화
df.reset_index(inplace=True)

In [9]:
# label 컬럼을 생성하여 1을 대입
df['label'] = 1
# 해당하는 행의 질문과 답변은 정상적인 답변입니다.

In [10]:
# 상담사 답변이 비어있는 행 제거
df = df[df['상담사답변'].str.strip() != '']
df = df.reset_index(drop=True)

In [11]:
# 컬럼 이름 바꾸기
df.rename(columns={
    '고객질문(요청)' : '고객질문'
}, inplace=True)

In [12]:
df.head()

,index,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문,상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스,label
0,0,다산콜센터,일반행정 문의,B2240,고객,1,지방세납부,,Q,지방세를 내려면 어떻게 해야됩니까,,,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.,지방세,지방세/세금,"지방세,세금",1
1,6,다산콜센터,일반행정 문의,B2240,고객,7,지방세납부,,Q,은행을 직접방문해도 됩니까,,,방문납부도 가능합니다.,은행,은행/공공기관,"은행,공공기관",1
2,12,다산콜센터,일반행정 문의,B2240,고객,13,지방세납부,,Q,버스로 가는 방법도 있습니까,,,도보로 가시는게 빠를 것 같습니다.,버스,버스/교통수단,"버스,교통수단",1
3,14,다산콜센터,일반행정 문의,B2240,고객,15,지방세납부,,Q,다른 납부방법도 있습니까,,,위택스 사이트에서 납부하실수 있습니다.,,납부방법/지방세,,1
4,16,다산콜센터,일반행정 문의,B2240,고객,17,지방세납부,,Q,사이트 주소가 어떻게 됩니까,,,www.wetax.go.kr 입니다.,사이트,납부방법/지방세/ 위텍스/ 납부,"사이트,납부",1

In [13]:
# label이 0인 데이터들을 생성 -> 기존의 질문과 답변에서 질문은 그대로 유지한채
# 원래의 답변을 제외한 다른 랜덤한 답으로 채운다
answers_list = df[['고객질문', '상담사답변']].values.tolist()
answers_list

[['지방세를 내려면 어떻게 해야됩니까', '이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.'],
 ['은행을 직접방문해도 됩니까', '방문납부도 가능합니다.'],
 ['버스로 가는 방법도 있습니까', '도보로 가시는게 빠를 것 같습니다.'],
 ['다른 납부방법도 있습니까', '위택스 사이트에서 납부하실수 있습니다.'],
 ['사이트 주소가 어떻게 됩니까', 'www.wetax.go.kr 입니다.'],
 ['다른곳에서는 납부할수 없습니까', '이용하시는 은행의 사이트에서도 지방세 납부가 가능합니다.'],
 ['지방세는 조회할 수 있습니까', '간단한 본인확인 후 안내해드리겠습니다.'],
 ['어떻게 납부합니까', '온라인으로는 위택스나 은행 홈페이지에서 가능합니다.'],
 ['사이트 주소가 어떻게 됩니까', 'OOOO.OOO.go.kr 입니다.'],
 ['서울시주최 페스티벌 예매해놨는데 예정대로 진행됩니까', '현재로썬 진행될 예정입니다.'],
 ['코로나로 다른 축제들은 취소됐는데 이건 취소 안됩니까', '네 철저한 방역수칙하에 진행할 예정입니다.'],
 ['환불할수 있습니까', '예매사이트 통해서 환불하실 수 있습니다.'],
 ['환불수수료 있습니까', '공연 일주일 전까진 10 수수료가 있습니다.'],
 ['코로나때문에 못가는건데도 수수료 내야합니까', '네 규정상 어쩔수 없습니다.'],
 ['참석했다가 코로나 걸리면 보상해줍니까', '철저한 방역수칙으로 진행하기에 걱정 안하셔도 됩니다.'],
 ['그래도 걸리면 보상해줍니까', '그 부분에 대해서는 개인이 조심을 하셔야기때문에 서울시에서는 따로 보상을 해드리진 않습니다.'],
 ['확산세가 더 강해지면 취소될 가능성 있습니까', '확산세가 심하면 취소 될 수도 있습니다.'],
 ['그럼 전액 환불되는겁니까', '네 맞습니다.'],
 ['청년저축계좌 지금 신청할 수 있습니까', '죄송하지만 이미 신청기간이 지났습니다.'],
 ['그럼 다른 정책은 없습니까', '희망두배 청년통장은 신청하실수 있습니다.'],
 ['그건 뭡니까', '청년저축계좌랑 비슷한 정책입니다.'],
 ['서울시민 대상입니까', '네 맞습니다.'],
 ['얼마를 추가 적립해줍니까', '저축액을 두 배로 적립해줍니다.'],
 ['모집인원은 어떻게 됩니까', '총 3천명입니다.'],
 ['신청기간은 언제까지입니까', '이번달 24일까지 신청기간이니 서둘러 신청해주세요.'],
 ['네 주소지가 서울이면 되는겁니까', '네 서울거주자이시면서 만 18세 34세 이하의 청년 대상입니다.'],
 ['그럼 총 어느정도 혜택을 받을 수 있습니까',
  '매달 10만원 저축이시면 장려금 30만원 지원받으셔서 3년 후 1 440만원을 마련하실 수 있습니다.'],
 ['3년동안 계속 10만원씩 해야합니까', '네. 청년저축계좌 유지조건으로 3년간 근로활동을 계속 하셔야 합니다.'],
 ['일도 쉬면 안됩니까', '네 근로장려 목적이기때문에 근로활동의 공백이 생기지 않도록 주의하셔야 합니다.'],
 ['또 다른 조건 있습니까', '다른 조건으로는 3년안에 국가공인자격증 1개 이상을 취득해야 합니다.'],
 ['저희가 작년에 결혼했는데 신혼부부 조건이 맞습니까', '네 결혼 7년 이내 부부는 신혼부부에 해당합니다.'],
 ['대출 상품이 뭐가 있습니까', '임대차 보증금 지원사업과 버팀목 전세자금 대출이 있습니다.'],
 ['어떤 은행에서 받을 수 있습니까', '하나은행 국민 신한은행을 통해서 받으실 수 있습니다.'],
 ['버팀목 대출 받으려면 조건이 있습니까', '두분 합산 연소득이 9천 7백만원 이하셔야 합니다.'],
 ['서울소재 주택만 가능한겁니까', '네 서울시 관내 소재하는 주택만 대상이 되십니다.'],
 ['대출한도는 어떻게 됩니까', '최대 2억원까지 대출 가능하십니다.'],
 ['100 다 대출받을 수 있습니까', '전세보증금의 90 까지만 대출 받으실 수 있습니다.'],
 ['그럼 나머지 10 에 대해서는 그냥 대출을 받을 수 있습니까', '네 은행 상품으로 대출 받으셔서 주택 마련하셔도 됩니다.'],
 ['그럼 그 한정된 곳에서 집을 찾아야합니까', '네. 하지만 해당안하는 집이 매우 한정적이라 큰 제한은 아닐겁니다.'],
 ['대출 한도는 어떻게 됩니까', '최대 2억원까지 받으실 수 있습니다.'],
 ['금리는 얼마입니까', '연 3.15 입니다.'],
 ['그렇게 낮은편이 아닌데 다른 혜택은 없습니까', '서울시에서 아치보전 금리를 지원하여 그만큼 차감해주는 사업을 진행하고 있습니다.'],
 ['그게 뭡니까', '기본금리에서 이차보전 금리를 차감한 본인 부담 금리가 1 이하인 경우에는 1 를 적용하는 것입니다.'],
 ['그럼 1 이율입니까', '네 맞습니다.'],
 ['대출기간은 어떻게 됩니까', '기본 2년에 2년 더 연장하실 수 있습니다.'],
 ['5월에 퇴사 했는데 연말정산 해야합니까', '네 대상자이십니다.'],
 ['제가 혼자서는 안해봤는데 혼자 해야합니가', '네 국세청 홈페이지에서 간편하게 안내해드리니까 어려움 없이 하실 수 있습니다.'],
 ['제가 준비해야할 것은 없습니까', '전년도 고용보험 납입 내역 준비하셔야 합니다'],
 ['그건 어디서 확인할 수 있습니까', '전 직장에 요청하시면 됩니다.'],
 ['안좋게 나왔는데 다른방법은 없습니까', '있습니다. 근로복지공단에서 조회 확인 가능합니다.'],
 ['그리고 국세청에서 신청하면 됩니까', '네 맞습니다.'],
 ['공인인증서 필요합니까', '없으시면 회원가입 하시면 됩니다.'],
 ['그럼 공인인증서 없어도 되는겁니까', '네 없으시면 휴대폰 인증 하시면됩니다..'],
 ['연말정산 환급 언제됩니까', '매년 2월에 정산해드립니다.'],
 ['제가 올해 안경을 구입했는데 환급됩니까', '네 의료비로 구분되어 소득공제 됩니다.'],
 ['이것도 간소화 서비스로 확인됩니까', '이 부분은 직접 입력해주셔야 합니다.'],
 ['직접 해야됩니까', '네. 누락항목에 대해서는 확인하시고 직접 입력해주셔야 합니다.'],
 ['신용카드 내역은 어떻게 됩니까', '신용카드 내역은 자동으로 카드사에서 넘어오기때문에 입력 안하셔도 됩니다.'],
 ['이번에 문화비 소득공제도 추가되었다던데 맞습니까', '네 올해부터 박물관 미술관 입장료 문화비도 소득공제에 추가되었습니다.'],
 ['얼마나 환급받을 수 있습니까', '연간 100만원 한도 내에서 결제 금액의 30 를 공제해줍니다.'],
 ['최대 100만원까지입니까', '네 맞습니다.'],
 ['월세 공제도 받을 수 있습니까', '월세금액의 10 세액공제 받을 수 있습니다.'],
 ['아직입니다. 어떻게 신고합니까', '먼저 경찰서 방문하셔서 분실신고를 해주시면 됩니다.'],
 ['챙겨가야할 거 있습니까', '신분증 지참하셔야 합니다.'],
 ['재발급은 어떻게 받습니까', '운전면허 시험장 가셔서 재발급 서류 작성하시면 됩니다.'],
 ['수수료는 얼마입니까', '수수료는 7 500원 입니다.'],
 ['재발급 받는데 얼마나 걸립니까', '보통 30분내외로 가능합니다.'],
 ['분실신고도 운전면허 시험장에서 해도 됩니까', '네 가능합니다.'],
 ['혹시 영문으로 운전면허증 발급도 됩니까', '네 19년 부터 영문 면허증 발급도 가능합니다.'],
 ['그럼 국제운전면허증 따로 발급 안해도됩니까', '일부 국가에서는 별도 국제운전면허증 없이도 사용 가능합니다.'],
 ['어느 국가인지 어디서 확인합니까', '경찰청 사이트에서 확인가능합니다.'],
 ['보건증 무인발급기로 출력할 수 있습니까', '보건증은 모든 보건소에서 지원하는게 아니라서 검사받은 보건소 확인이 필요합니다.'],
 ['서울에는 어디서 가능합니까',
  '서울은 강남구 도봉구 관내 보건소에서 받으신 경우 관내 무인발급기를 통해서 발급 가능합니다. 또 인터넷으로도 발급가능합니다.'],
 ['그럼 보건소 꼭 방문 해야합니까', '네 맞습니다.'],
 ['그 다음은 어떻게합니까', '검진후 신청서 작성하셔서 신분증과 같이 제출하시면 됩니다.'],
 ['청소년인데 학생증도 됩니까', '학생증도 가능합니다.'],
 ['그리고 온라인으로 수령할수 있는겁니까', '네 정부24이용하시면 출력가능합니다.'],
 ['얼마나 걸립니까', '보통 5일정도 소요됩니다.'],
 ['나이가 중요합니까', '청년농에 대한 지원사업이 따로 있어서 구분해 안내드리려합니다.'],
 ['정착장려금은 뭡니까', '연고지 없는 분들 대상으로 초반에 적응할 수 있도록 지원금을 주는 제도 입니다.'],
 ['얼마나 지원 받을 수 있습니까', '가구당 480만원 지원 받으실 수 있습니다.'],
 ['농업과 관련되서만 사용할 수 있는 지원금입니까', '네 농업경영을 위한 용도로만 사용가능합니다.'],
 ['신청은 어디서 합니까', '신청하시는 읍 면사무소에서 하시면 됩니다.'],
 ['신청 기간은 언제입니까', '상반기 4월 하반기 9월에 매년 신청을 받습니다.'],
 ['제가 귀촌한지 2년 되었는데 신청할 수 있습니까', '이 지원정책은 귀농정착 후 3년 경과한 시점부터 신청하실 수 있습니다.'],
 ['3년 채우려면 세 달 정도 남았는데 지금 신청 안됩니까', '신청이 9월이니까 이번에는 신청 자격이 안됩니다.'],
 ['그럼 다음 신청은 언제입니까', '내년 4월에는 신청 가능합니다.'],
 ['혹시 내년에 지원을 받고 다른 지역으로 이사를 가도 됩니까',
  '지원 받은 후 5년 이내에 다른 지역으로 이주하시면 지원취소 및 지원금 회수가 됩니다.'],
 ['그럼 5년간 지원금을 받는겁니까', '네 맞습니다.'],
 ['연간 지원금이 얼마입니까', '연간 480만원씩 지원됩니다.'],
 ['나이 제한은 따로 없습니까', '만20세 이상 60세 이하로 제한되어 있습니다.'],
 ['안녕하세요. 제가 이번에 공무원 시험을 봤는데 시험 결과는 언제 나옵니까', '결과는 9월 20일로 예정되어있습니다.'],
 ['좀 더 빨리 공고내주시면 안됩니까', '죄송하지만 안됩니다.'],
 ['왜 안됩니까', '절차에 따라 검토 후 공고가 나가는거라 시간이 걸립니다.'],
 ['요새 컴퓨터로하면 금방되지 않습니까', '자세한 사항은 말씀드릴수가 없습니다.'],
 ['그럼 제 점수만 먼저 알수 없습니까', '개개인 점수를 알려드릴수는 없습니다.'],
 ['제가 마킹을 잘 못한게 있는거같아서 너무 불안데 확인할 수 없습니까',
  '마킹 의문사항이 있으시면 사전점수 공개기간에 확인하시고문의주시면 확인하실 수 있으세요.'],
 ['사전점수 공개는 언제입니까', '9월 12일 입니다.'],
 ['그때 제 점수는 확인할 수 있는겁니까', '네 확인가능합니다.'],
 ['그럼 등수도 확인할 수 있습니까', '등수는 확인할 수 없습니다.'],
 ['농촌일손돕기 봉사 신청하려고합니다.', '네. 1365자원봉사포털에서 신청 가능하십니다.'],
 ['봉사활동은 어디서합니까', '서울시내 농가에서 진행합니다.'],
 ['과수농장으로 갈 수 있습니까', '과수뿐만 아니라 채소 화훼 농가도 참여 가능합니다.'],
 ['어떤일을 하게 됩니까', '이번에 홍수로 인해 농작물 훼손이 많습니다. 피해 농가에 방문해서 농사 보조업무를 하게 됩니다.'],
 ['농사 경험 없어도 가능합니까', '네 가능합니다.'],
 ['준비물은 따로 있습니까', '편한 복장과 도시락과 간식등 챙겨오시면 됩니다.'],
 ['중식은 제공 안됩니까', '네 중식은 제공되지 않기때문에 개인 도시락 지참하셔야 합니다.'],
 ['봉사활동 하고 확인증 받을 수 있습니까', '네 받으실 수 있습니다.'],
 ['근데 일단 하루만 신청하고 싶은데 하루만 해도됩니까', '네 신청하실때 날짜를 지정하실 수 있습니다.'],
 ['주말농장 신청하려고 합니다.', '현재는 신청기간이 마감되었습니다.'],
 ['다음 신청은 언제입니까', '매년 1월마다 선착순으로 접수 받고 있습니다.'],
 ['그럼 미리 알아놓으려고 하는데 주말농장 분양은 몇 평이나 가능합니까', '세대 당 1구획 단체는 3구획까지 분양 가능합니다.'],
 ['가격은 어떻게 됩니까', '연 7 10만원으로 신청하시는 지역마다 다릅니다.'],
 ['몇명이나 모집합니까', '100명씩 모집합니다.'],
 ['작물은 저희가 심고싶은거 심어도 됩니까',
  '네 가능합니다. 하지만 아무래도 환경이나 재배에 대한 교육도 함께 진행하기 때문에 시에서 추천하는 작물을 심으시길 권장드립니다.'],
 ['저희가 수확한 작물은 집에가져가서 먹어도 됩니까', '네 물론입니다.'],
 ['매주 농장에 방문해야합니까', '의무는 아니지만 매주 방문하시는것을 추천드립니다.'],
 ['어디서 할 수 있습니까', '구청 자동차 등록 민원실에서 접수하시면 됩니다.'],
 ['그 다음엔 어떻게 합니까', '취등록세 납부하셔야 합니다.'],
 ['카드 결제됩니까', '네 현금 및 카드 납부 가능합니다.'],
 ['카드 결제하면 수수료 있습니까', '국민은행 외 타행카드는 수수료가 발행됩니다.'],
 ['그 다음은 어떻게 합니까', '그 다음 같은 장소에서 채권 구입을 하셔야합니다.'],
 ['채권 얼마정도 합니까', '13만원 입니다.'],
 ['카드 결제됩니까', '아뇨. 채권은 현금만 가능합니다.'],
 ['돈좀 챙겨가야겠네요. 그럼 명의변경하는데 얼마나 걸립니까', '1시간 정도 소요됩니다.'],
 ['둘다 받고싶은데 하나로 합쳐서 받을 수 있습니까', '네 가능합니다.'],
 ['금액은 어떻게 됩니까', '3 300원에 우편료 2 400원 추가됩니다..'],
 ['직접 수령하러가도 됩니까', '네. 문의주신 번호로 안내가 가면 수령하시러 방문하시면 됩니다.'],
 ['어떤 방식이 있습니까', '가상계좌로 입금하시거나 수령하실때 현장결제도 가능합니다.'],
 ['안녕하세요. 저 장학생 문의하려 합니다.', '네 말씀하십시오.'],
 ['혹시 충남 한울타리 장학생이랑 희망드림 장학생이랑 중복 선발 가능합니까', '아니요. 중복선발은 배제하고 있습니다.'],
 ['장학생 신청기간이 어떻게 됩니까', '신청기간은 9월 3일부터 24일까지 입니다.'],
 ['신청방법은 어떻게 하면 됩니까', '신청방법은 충남인재육성재단에 개인정보 입력하시고 신청하시면 됩니다.'],
 ['네. 그런데 제가 충남으로 전입기간이 1년이 채 안되었는데 신청가능합니까',
  '네 가능하십니다. 접수 마감일까지 전입기간 1년미만인 대학생 대상으로 진행하고 있습니다.'],
 ['마지막으로 질문 하나만 더 드릴게요. 장학금액은 얼마나 됩니까', '1인에 200만원 입니다.'],
 ['현금으로 지급됩니까', '선발대상자 분 개인 계좌번호로 입금될 예정입니다.'],
 ['제가 기사를 통해서 원래 자녀 3인이상 받던 혜택을 올해부터 2인만 되도 받을 수 있다고 하더던데 맞습니까',
  '네. 맞습니다. 현재 협의 진행중이라 아마 내달부터는 적용되실 수 있으실겁니다.'],
 ['신청기간이 어떻게 됩니까', '신청기간은 이번달 말까지 입니다.'],
 ['저 최근 이사를 해서 주소 변경 가능합니까', '네 주소 불러주시면 바로 수정해드릴게요.'],
 ['안녕하세요. 유기동물 복지 관련 문의드리려합니다.', '네 담당자분으로 연결해 드리겠습니다.'],
 ['혹시 이 아이들을 위해 지원해주는 거 있습니까', '정확한 위치 알려주시면 저희 직원이 나가서 담당 병원으로 인계해드릴겁니다.'],
 ['네 하나더 여쭤볼게요. 그 어미고양이 중성화 관련 지원사업은 없습니까',
  '있습니다. 저희가 100 중성화 비용을 다 지원은 안되고 보호자나 구조하시는 분께서 부담을 해주시는 조건에 지원을 해주고 있습니다.'],
 ['지원은 얼마나 됩니까', '중성화 비용의 30 지원해주고 있습니다.'],
 ['그럼 나머지는 제가 부담해야하는겁니까', '네 맞습니다.'],
 ['가산도서관 지금 이용 불가입니까', '책 대여는 가능하신데 자유열람실은 이용하실 수 없습니다.'],
 ['언제까지입니까', '코로나로 인한거라 추세를 지켜봐야할거같습니다.'],
 ['그럼 이번에 사물함 결제한건 어떻게 됩니까', '이용하시지 못한 일수에 대한 환불이 진행될 예정입니다.'],
 ['책 대여는 몇시까지 할 수 있습니까', '평일은 8시까지 토요일은 6시까지 대여 가능합니다.'],
 ['최대 몇권까지 대여할 수 있습니까', '5권까지 대여가능합니다.'],
 ['기간은 얼마나 대여할 수 있습니까', '2주간 대여 가능합니다.'],
 ['혹시 연체하면 어떻게 됩니까', '연체 일수만큼 다음 대여가 금지됩니다.'],
 ['반납은 어디에 하면 됩니까', '2층 데스크에 반납하시면 됩니다.'],
 ['8시 이후에는 반납을 못합니까', '가능합니다. 도서관 정문 앞에 무인반납기가 있어서 이용하시면 됩니다.'],
 ['공고문을 봤는데 3개월간 사무보조 업무라고 되어있는데 어떤 기관에서 일을 하는겁니까', '공공기관으로 배정될 예정입니다.'],
 ['지금은 확실히 모르는겁니까', '네 지금은 확실히 말씀드리기 어렵고 지원서 보고 배치 될 예정입니다.'],
 ['저는 체육문화 부서에서 업무를 보고싶은데 어떻게 하면되겠습니까',
  '자기소개서에 그 분야 강점을 서술해주시면 고려할 것으로 예상됩니다.'],
 ['근데 아직 가채점만 한 상태라 자격증 취득이라고 해도 됩니까', '아직 미취득 상태시면 취득 예정이라고 비고란에 써주시면 됩니다.'],
 ['네 친구랑 같이 지원해도 됩니까', '같이 지원은 가능하시지만 많은 분들이 지원해주신거라 같이 근무를 하실수는 없을수도 있습니다.'],
 ['농기계 대여 하려합니다.', '넵 농기계 파트로 연결해 드리겠습니다.'],
 ['아니 지금이 수확철인데 다음달까지 기다려야합니까', '죄송합니다. 재원이 한정적이라서 어쩔수가 없습니다.'],
 ['시에서 몇 대를 보유하고 있습니까', '10대 보유중인데 지금 다 대여되었습니다.'],
 ['홍보를 그렇게 많이 했으면서 10대 밖에 지원을 안해주면 10명만 지원받으란 얘깁니까', '죄송합니다. 개선하도록 하겠습니다.'],
 ['어떤 대책입니까', '농기계 대여는 힘들지만 농작업지원단을 파견하고 있습니다. 수확철에 이용하시면 도움이 되실 거같습니다.'],
 ['네 지원받겠습니다. 이달 말에 받을 수 있습니까', '네 인력 확보해서 안내드리겠습니다.'],
 ['서울시민체육센터 지금 운영합니까', '네 일부 강좌만 인원제한으로 운영하고 있습니다.'],
 ['무슨 강좌 운영중입니까', '요가와 테니스 운영중입니다.'],
 ['테니스 오후 시간대 참여할 수 있습니까', '네 오후 시간대는 7시 9시 두 수업 진행중입니다.'],
 ['운동화 밖에서 신은것도 괜찮습니까', '실내에서 사용하실 운동화 따로 준비하셔야 합니다.'],
 ['샤워시설 따로 준비되어 있습니까', '네. 약간의 비용 발생합니다.'],
 ['얼마입니까', '이용시 3000원 입니다.'],
 ['네 회원가입 어떻게 합니까', '고용센터 홈페이지에서 바로 회원가입가능합니다.'],
 ['회원가입 하면 바로 이용가능합니까', '회원가입하고 카드 신청하면 자택 우편으로 발송될거에요'],
 ['그럼 제가 언제쯤 받아볼수 있습니까', '2주 정도 소요됩니다.'],
 ['더 빨리 받아볼 순 없습니까', '접수 후 일괄로 배송되는거라 양해바랍니다.'],
 ['제가 고용센터로 직접 받으러 갈 순 없습니까',
  '회원가입하실때 선택하실 수 있습니다. 직접 수령 선택하시고 수령하실 센터 지정하시면 됩니다.'],
 ['고용센터 정확한 위치가 어떻게 됩니까', '고용센터 2층 안내데스크에서 수령하시면 됩니다.'],
 ['운영시간은 어떻게 됩니까', '오후 6시까지입니다.'],
 ['컴퓨터 자격관련 강좌를 듣고싶은데 추천해주실거 있으십니까', '컴퓨터 활용능력 캐드 모스마스터 과정이 있습니다.'],
 ['컴퓨터 활용능력 1급도 합니까', '네 1급 강좌도 있습니다.'],
 ['그걸로 신청하고 싶은데 비용이 어떻게 됩니까', '36만원 중 본인부담금 30 입니다.'],
 ['아 그럼.. 10만원정도 합니까', '정확히 10만 8천원에 교재는 별도 입니다.'],
 ['아 교재는 어디서 삽니까', '가까운 서점이나 온라인으로도 구매하실수 있습니다.'],
 ['독서평 공모전에 지원하려고 하는데 공고문에 올라와있는 도서 리스트 중에서만 선택할 수 있습니까',
  '아닙니다. 올려놓은것은 예시여서 그 외 작품을 선정하셔도 무방합니다.'],
 ['아 그럼 인문학 분야에서 아무거나 선택해서 써도 됩니까', '네 맞습니다.'],
 ['페이지수 제한은 없습니까', 'A4 2 3장 내외입니다.'],
 ['하나 더 여쭤보겠습니다. 마감일을 못지키면 어떻게 됩니까', '마감일 이후에 도착하는 건은 저희가 안타깝지만 수상에서 제외됩니다.'],
 ['그렇군요. 이메일로 보내도 됩니까', '네 이메일로 보내주셔도 됩니다.'],
 ['혹시 스팸으로 확인이 안되어지면 어떻게 합니까', '마감일 이후에 수신확인이 안되어 있다면 연락 부탁드립니다.'],
 ['직접 수신확인 해야합니까', '네. 저희도 수시로 확인해보고 있지만 혹시 누락될 경우가 있습니다.'],
 ['그럼 혹시 시흥시에는 있습니까', '시흥시에 00커피에서 저녁 7시에 진행되는 강좌가 있습니다.'],
 ['시흥까지 가려면 7시까지는 못갈꺼같은데 다른 강좌는 없습니까', '네 현재까지는 강좌오픈 예정이 되어있지 않습니다.'],
 ['아 어떤 강좌 있습니까', '한식조리기능사 강좌와 도자기 클래스 강좌 있습니다.'],
 ['한식조리기능사 자격증 취득도 할 수 있습니까', '네 시험과정 진행하고 있습니다.'],
 ['혹시 중식조리기능사는 같이 준비할 수 있습니까', '아뇨 현재 한식만 가능합니다.'],
 ['한식조리기능사 강좌 비용이 얼마입니까', '50만원 중 본인부담비 50 입니다.'],
 ['재료비 포함입니까', '네 재료비는 포함입니다.'],
 ['그럼 제가 준비해 가야할건 없습니까', '음. 앞치마 정도만 챙겨오시면 될거 같습니다.'],
 ['네 포스터를 봤는데 사진반이 있던데 저 사진을 정말 못찍는데 참여 가능합니까',
  '네. 가능합니다. 초보자를 위한 강좌라 기본지식 없으셔도 무리없이 들으실 수 있습니다.'],
 ['신청은 언제부터 받는겁니까', '다음주 월요일 9시부터 선착순으로 접수를 받고 있습니다.'],
 ['정원이 몇명입니까', '정원은 20명 입니다.'],
 ['하나만 더 여쭤보겠습니다. 준비물에 개인 dslr을 지참해야한다고 하던데 필름카메라는 안됩니까',
  '네 이번 강좌는 디지털 카메라 기술에 대한 거라.. 필름카메라로는 강좌를 들으시는데 한계가 있으실꺼 같습니다.'],
 ['네 오늘중으로 연락 주십니까', '네 오늘 6시 이전에는 연락드릴게요'],
 ['어떤 사업이 있습니까', '어떤 피해를 보셨는지에 따라 다릅니다.'],
 ['이번에 중복으로 지원을 받을 수 있습니까', '네. 이번에 특수경우로 구분되어져서 중복 지원 가능합니다.'],
 ['기초수급자 신청하려고 합니다.', '네 먼저 신원조회 해드리겠습니다.'],
 ['그냥 신청해주시면 안됩니까', '호적상에 남아있어서 임의로 그렇게 진행을 해드릴 수가 없습니다.'],
 ['아니 같이 살지도 않고 그 애가 돈을 벌던 저랑은 상관이 없는데 왜 신청이 안된다는 겁니까',
  '그래도 서류상 어쩔 수 가 없습니다.'],
 ['다른 방안 없습니까', '어머님이나 아드님 둘중에 한분이 주소지를 옮기시면 혜택을 받으실 수 있습니다.'],
 ['운전면허 갱신하려합니다.', '교통과로 문의하시면 됩니다.'],
 ['뭐 준비해가야 합니까', '운전면허 신체검사 발급증과 사진2매 지참하시면 됩니다.'],
 ['증명사진으로 가져가면 됩니까', '네 맞습니다.'],
 ['자취하는데 그럼 제가 세대주 맞습니까', '네 맞습니다.'],
 ['이번에 한국사 시험 미뤄집니까', '아직 미정이지만 미뤄질 확률이 높아보입니다.'],
 ['언제쯤 공고합니까', '이번주 중에 공고 올라갈거같습니다.'],
 ['그럼 다음 시험일정은 어떻게 됩니까', '한 달 미뤄질 것으로 예상됩니다.'],
 ['그럼 신청해놓은 기록은 남아있습니까', '네. 기존에 신청하신 내역과 동일하게 진행됩니다.'],
 ['혹시 환불하려면 어떻게 합니까', '로그인하시고 환불신청하시면 됩니다.'],
 ['환불 수수료가 있습니까', '아니요. 코로나로 인해 연기때문에 취소하시는거에 대해서 수수료를 부과하지 않습니다.'],
 ['환불기간은 어떻게 됩니까', '시험 보기 일주일 전까지 가능합니다.'],
 ['시험장소 다시 확인해 주시겠습니까', '홈페이지 마이페이지에서 확인하실 수 있습니다.'],
 ['10년으로 만들수 있습니까', '8세미만 아이는 5년짜리로 발급하셔야 됩니다.'],
 ['비용이 얼마입니까', '3만원 입니다.'],
 ['준비물은 뭐 있어야 합니까', '증명사진이랑 보호자 신분증 있으시면 됩니다.'],
 ['증명사진은 집에서 셀프로 찍어도 됩니까', '네 가능하십니다.'],
 ['토요일도 발급이 가능합니까', '시청마다 달라서 문의를 따로 하셔야 합니다.'],
 ['토요일은 발급 시간이 어떻게 됩니까', '토요일은 오전9시부터 오후 1시까지 입니다.'],
 ['발급은 얼마나 걸립니까', '업무량에 따라 다르지만 평균 3 5일정도 걸립니다.'],
 ['여권재발급 받으려고 하는데요 신규디자인으로 받을 수 있습니까', '아직 신규 디자인 발급은 불가능하십니다.'],
 ['언제부터 신규 디자인으로 받을 수 있습니까', '20년 하반기부터 발급가능합니다.'],
 ['재발급 준비물은 무엇입니까', '사진1장과 신청서 기존여권입니다.'],
 ['대리 수령은 가능합니까', '네 수령은 대리로 가능합니다.'],
 ['대리수령할때 준비해갈게 있습니까', '대리수령시 신청인 신분증과 대리인신분증 접수증 있으시면 됩니다.'],
 ['접수하고 얼마나 기다려야 합니까', '영업일 기준 3일째에 받아보실 수 있습니다.'],
 ['재발급 비용은 얼마입니까', '5만원입니다.'],
 ['직접방문해야 됩니까', '네 가까운 동 면사무소 가셔서 확정일자 받으시면 됩니다.'],
 ['챙겨가야할 서류 있습니까', '계약서랑 신분증 챙겨가시면 됩니다.'],
 ['점심 시간 언제입니까', '통상 12시부터 1시 이지만 로테이션 근무라서 업무처리에 지장 없으실겁니다.'],
 ['몇시까지 합니까', '6시까지 운영합니다.'],
 ['확정일자 바로 나옵니까', '네 그 자리에서 바로 나실겁니다.'],
 ['지방세를 내려면 어떻게 해야되요', '이용하시는 은행의 사이트에서 지방세 납부가 가능하세요.'],
 ['은행을 직접방문해도 돼요', '방문납부도 가능하세요.'],
 ['버스로 가는 방법도 있어요', '도보로 가시는게 빠를거 같아요.'],
 ['다른 납부방법도 있나요', '위택스 사이트에서 납부하실수 있어요.'],
 ['사이트 주소가 어떻게 돼요', 'www.wetax.go.kr 입니다.'],
 ['다른곳에서는 납부할수 없나요', '이용하시는 은행의 사이트에서도 지방세 납부가 가능하세요.'],
 ['지방세는 조회할 수 있어요', '간단한 본인확인 후 안내해드릴게요.'],
 ['어떻게 납부해요', '온라인으로는 위택스나 은행 홈페이지에서 가능하세요.'],
 ['사이트 주소가 어떻게 돼요', 'OOOO.OOO.go.kr 입니다.'],
 ['서울시주최 페스티벌 예매해놨는데 예정대로 진행되나요', '현재로썬 진행될 예정이에요.'],
 ['코로나로 다른 축제들은 취소됐는데 이건 취소 안되나요', '네 철저한 방역수칙하에 진행할 예정이에요.'],
 ['환불할수 있어요', '예매사이트 통해서 환불하실 수 있어요.'],
 ['환불수수료 있나요', '공연 일주일 전까진 10 수수료가 있어요.'],
 ['코로나때문에 못가는건데도 수수료 내야돼요', '네 규정상 어쩔수 없어요.'],
 ['참석했다가 코로나 걸리면 보상해주나요', '철저한 방역수칙으로 진행하기에 걱정 안하셔도 돼요.'],
 ['그래도 걸리면 보상해주나요', '그 부분에 대해서는 개인이 조심을 하셔야기때문에 서울시에서는 따로 보상을 해드리진 않아요.'],
 ['확산세가 더 강해지면 취소될 가능성 있나요', '확산세가 심하면 취소 될 수도 있어요.'],
 ['그럼 전액 환불되나요', '네 맞습니다.'],
 ['청년저축계좌 지금 신청할 수 있나요', '죄송하지만 이미 신청기간이 끝났어요.'],
 ['그럼 다른 정책은 없나요', '희망두배 청년통장은 신청하실수 있어요.'],
 ['그건 뭐에요', '청년저축계좌랑 비슷한 정책이에요.'],
 ['서울시민 대상이에요', '네 맞습니다.'],
 ['자세히 설명해 주시겠어요',
  '2 3년간 꾸준히 저축하는 서울청년 대상 본인 저축액 100 를 서울시 예산으로 추가 적립해주는 통장이에요.'],
 ['얼마를 추가 적립해주나요', '저축액을 두 배로 적립해 줄거에요.'],
 ['모집인원은 어떻게 되나요', '총 3천명이에요.'],
 ['신청기간은 언제까지에요', '이번달 24일까지 신청기간이니 서둘러 신청해주세요.'],
 ['네 주소지가 서울이면 되나요', '네 서울거주자이시면서 만 18세 34세 이하의 청년 대상이세요.'],
 ['그럼 총 어느정도 혜택을 받을 수 있나요',
  '매달 10만원 저축이면 장려금 30만원 지원받으셔서 3년 후 1 440만원을 마련하실 수 있어요.'],
 ['3년동안 계속 10만원씩 해야하나요', '네. 청년저축계좌 유지조건으로 3년간 근로활동을 계속 하셔야해요.'],
 ['일도 쉬면 안되나요', '네 근로장려 목적이기때문에 근로활동의 공백이 생기지 않도록 주의하셔야 해요.'],
 ['또 다른 조건 있나요', '다른 조건으로는 3년안에 국가공인자격증 1개 이상을 취득하셔야 되요.'],
 ['저희가 작년에 결혼했는데 신혼부부 조건이 맞나요', '네 결혼 7년 이내 부부는 신혼부부에 해당됩니다.'],
 ['대출 상품이 뭐가 있나요', '임대차 보증금 지원사업과 버팀목 전세자금 대출이 있어요.'],
 ['어떤 은행에서 받을 수 있나요', '하나은행 국민 신한은행을 통해서 받으실 수 있어요.'],
 ['버팀목 대출 받으려면 조건이 있어요', '두분 합산 연소득이 9천 7백만원 이하이셔야 돼요.'],
 ['서울소재 주택만 가능하나요', '네 서울시 관내 소재하는 주택만 대상이에요.'],
 ['대출한도는 얼마에요', '최대 2억원까지 대출 가능하세요.'],
 ['100 다 대출받을 수 있나요', '전세보증금의 90 까지만 대출 받으실 수 있어요.'],
 ['그럼 나머지 10 에 대해서는 일반 대출을 받을 수 있나요', '네 은행 상품으로 대출 받으셔서 주택 마련하셔도 돼요.'],
 ['그럼 그 한정된 곳에서 집을 찾아야하나요', '네. 하지만 해당안하는 집이 매우 한정적이라 큰 제한은 아닐거에요.'],
 ['대출 한도는 어떻게 되나요', '최대 2억원까지 받으실 수 있어요.'],
 ['금리는 얼마에요', '연 3.15 에요.'],
 ['그렇게 낮은편이 아닌데 다른 혜택은 없나요', '서울시에서 아치보전 금리를 지원하여 그만큼 차감해주는 사업을 진행하고 있어요.'],
 ['그게 뭐에요', '기본금리에서 이차보전 금리를 차감한 본인 부담 금리가 1 이하인 경우에는 1 를 적용하는 거에요.'],
 ['그럼 1 이율이에요', '네 맞습니다.'],
 ['대출기간은 어떻게 돼요', '기본 2년에 2년 더 연장하실 수 있어요.'],
 ['5월에 퇴사 했는데 연말정산 해야돼요', '네 대상자이세요.'],
 ['제가 혼자서는 안해봤는데 혼자 해야되나요', '네 국세청 홈페이지에서 간편하게 안내해드리니까 어려움 없이 하실 수 있어요.'],
 ['제가 준비해야할 것은 없어요', '전년도 고용보험 납입 내역 준비하셔야 돼요.'],
 ['그건 어디서 확인할 수 있어요', '전 직장에 요청하시면 돼요.'],
 ['안좋게 나왔는데 다른방법은 없나요', '있어요. 근로복지공단에서 조회 확인 가능하세요.'],
 ['그리고 국세청에서 신청하면 되나요', '네 맞습니다.'],
 ['공인인증서 필요하나요', '없으시면 회원가입 하시면 돼요.'],
 ['그럼 공인인증서 없어도 되는건가요', '네 없으시면 휴대폰 인증 하시면 돼요.'],
 ['연말정산 환급 언제됩나요', '매년 2월에 정산해드려요.'],
 ['제가 올해 안경을 구입했는데 이것도 환급되나요', '네 의료비로 구분되어 소득공제 돼요.'],
 ['이것도 간소화 서비스로 확인되나요', '이 부분은 직접 입력해주셔야 해요.'],
 ['직접 해야되나요', '네. 누락항목에 대해서는 확인하시고 직접 입력해주셔야 해요.'],
 ['신용카드 내역은 자동인가요', '네. 신용카드 내역은 자동으로 카드사에서 넘어오기때문에 입력 안하셔도 돼요.'],
 ['이번에 문화비 소득공제도 추가되었다던데 맞아요', '네 올해부터 박물관 미술관 입장료 문화비도 소득공제에 추가됐어요.'],
 ['얼마나 환급해 주나요', '연간 100만원 한도 내에서 결제 금액의 30 를 공제될 거에요.'],
 ['최대 100만원까지에요', '네 맞습니다.'],
 ['월세 공제도 받을 수 있나요', '월세금액의 10 세액공제 받을 수 있어요.'],
 ['아직요. 어떻게 신고해요', '먼저 경찰서 방문하셔서 분실신고를 해주시면 돼요.'],
 ['챙겨가야할 거 있나요', '신분증 지참하셔야 해요.'],
 ['재발급은 어떻게 받나요', '운전면허 시험장 가셔서 재발급 서류 제출하시면 돼요.'],
 ['수수료는 얼마에요', '수수료는 7 500원이에요.'],
 ['재발급 받는데 얼마나 걸리나요', '보통 15분내외로 돼요.'],
 ['분실신고도 운전면허 시험장에서 해도 되나요', '네 가능하세요.'],
 ['혹시 영문으로 운전면허증 발급도 되나요', '네 19년 부터 영문 면허증 발급도 가능하세요.'],
 ['그럼 국제운전면허증 따로 발급 안해도돼요', '일부 국가에서는 별도 국제운전면허증 없이도 사용 가능해요.'],
 ['어느 국가인지 어디서 확인하나요', '경찰청 사이트에서 확인가능하세요.'],
 ['보건증 무인발급기로 출력할 수 있어요', '보건증은 모든 보건소에서 지원하는게 아니라서 검사받은 보건소 확인이 필요해요.'],
 ['서울에는 어디서 가능한가요',
  '서울은 강남구 도봉구 관내 보건소에서 받으신 경우 관내 무인발급기를 통해서 발급 가능하고 또 인터넷으로도 발급가능해요.'],
 ['그럼 보건소 꼭 방문 해야돼요', '네 맞습니다.'],
 ['그 다음은 어떻게하나요', '검진후 신청서 작성하셔서 신분증과 같이 제출하시면 돼요.'],
 ['청소년인데 학생증도 돼요', '학생증도 가능해요.'],
 ['그리고 온라인으로 수령할수 있어요', '네 정부24이용하시면 출력가능해요.'],
 ['얼마나 걸려요', '보통 5일정도 소요될거에요.'],
 ['나이가 중요한가요', '청년농에 대한 지원사업이 따로 있어서 구분해 안내드리려구요.'],
 ['정착장려금은 뭔가요', '연고지 없는 분들 대상으로 초반에 적응할 수 있도록 지원금을 주는 제도에요.'],
 ['얼마나 지원 받을 수 있어요', '가구당 480만원 지원 받으실 수 있어요.'],
 ['농업과 관련되서만 사용할 수 있는 지원금인가요', '네 농업경영을 위한 용도로만 사용가능하세요.'],
 ['신청은 어디서 하나요', '신청하시는 읍 면사무소에서 하시면 돼요.'],
 ['신청 기간은 언제에요', '상반기 4월 하반기 9월에 매년 신청을 받고있어요.'],
 ['제가 귀촌한지 2년 되었는데 신청할 수 있나요', '이 지원정책은 귀농정착 후 3년 경과한 시점부터 신청하실 수 있어요.'],
 ['3년 채우려면 8개월 정도 남았는데 지금 신청 안되나요', '신청이 내년 4월이니까 이번에는 신청 자격이 안됩니다.'],
 ['그럼 다음 신청은 언제에요', '9월에는 신청 가능하세요.'],
 ['혹시 내년에 지원을 받고 다른 지역으로 이사를 가도 되나요',
  '지원 받은 후 5년 이내에 다른 지역으로 이주하시면 지원취소 및 지원금 회수될거에요.'],
 ['그럼 5년간 지원금을 받는거에요', '네 맞습니다.'],
 ['연간 지원금이 얼마에요', '연간 480만원씩 지원돼요.'],
 ['나이 제한은 따로 없나요', '만20세 이상 60세 이하로 제한되어 있어요.'],
 ['안녕하세요. 제가 이번에 공무원 시험을 봤는데 시험 결과는 언제 나와요', '결과는 9월 20일로 예정되어있어요.'],
 ['좀 더 빨리 공고내주시면 안되나요', '죄송하지만 안됩니다.'],
 ['왜요', '절차에 따라 검토 후 공고가 나가는거라 시간이 걸려서요.'],
 ['요새 컴퓨터로하면 금방안돼요', '자세한 사항은 말씀드릴수가 없어요.'],
 ['그럼 제 점수만 먼저 알수 없나요', '개개인 점수를 알려드릴수는 없어요.'],
 ['제가 마킹을 잘 못한게 있는거같아서 너무 불안한데 확인할 수 없나요',
  '마킹 의문사항이 있으시면 사전점수 공개기간에 확인하시고문의주시면 확인하실 수 있어요.'],
 ['사전점수 공개는 언제에요', '9월 12일이에요.'],
 ['그때 제 점수는 확인할 수 있는거죠', '네 확인가능하세요.'],
 ['그럼 등수도 확인되나요', '등수는 확인할 수 없어요.'],
 ['농촌일손돕기 봉사 신청하려는데요.', '네. 1365자원봉사포털에서 신청 가능하세요.'],
 ['봉사활동은 어디서하나요', '서울시내 농가에서 진행되요.'],
 ['과수농장으로 갈 수 있어요', '과수뿐만 아니라 채소 화훼 농가도 참여 가능하세요.'],
 ['어떤일을 하게 되나요', '이번에 홍수로 인해 농작물 훼손이 많아서 피해 농가에 방문해서 농사 보조업무를 하게 될거에요.'],
 ['농사 경험 없어도 가능한가요', '네 가능합니다.'],
 ['준비물은 따로 있어요', '편한 복장과 도시락과 간식등 챙겨오시면 돼요.'],
 ['중식은 제공 안되는 거에요', '네 중식은 제공되지 않기때문에 개인 도시락 지참하셔야 해요.'],
 ['봉사활동 하고 확인증은 주는거죠', '네 받으실 수 있어요.'],
 ['근데 일단 하루만 신청하고 싶은데 하루만 해도되나요', '네 신청하실때 날짜를 지정하실 수 있어요.'],
 ['주말농장 신청하고싶은데요.', '현재는 신청기간이 마감됐어요.'],
 ['다음 신청은 언제에요', '매년 1월마다 선착순으로 접수 받고 있어요.'],
 ['그럼 미리 알아놓으려고 하는데 주말농장 분양은 몇 평이나 가능한가요', '세대 당 1구획 단체는 3구획까지 분양 가능해요.'],
 ['가격은요', '연 7 10만원으로 신청하시는 지역마다 달라요.'],
 ['몇명이나 모집하나요', '100명씩 모집해요.'],
 ['작물은 저희가 심고싶은거 심어도 되죠',
  '네 가능한데요 아무래도 환경이나 재배에 대한 교육도 함께 진행하기 때문에 시에서 추천하는 작물을 심으시길 권장드려요.'],
 ['저희가 수확한 작물은 집에가져도 되죠', '네 물론입니다.'],
 ['매주 농장에 방문해야되나요', '의무는 아니지만 매주 방문하시는것을 추천해요.'],
 ['어디서 할 수 있어요', '구청 자동차 등록 민원실에서 접수하시면 돼요.'],
 ['그럼 끝인가요', '취등록세 납부하셔야 해요.'],
 ['카드결제도 괜찮아요', '네 현금 및 카드 납부 가능하세요.'],
 ['카드 결제하면 수수료는요', '국민은행 외 타행카드는 수수료가 있어요.'],
 ['그 다음은 어떻게 해요', '그 다음 같은 장소에서 채권 구입을 하셔야해요.'],
 ['채권은 얼마에요', '13만원이에요.'],
 ['채권도 카드결제되요', '아뇨. 채권은 현금만 가능합니다.'],
 ['돈좀 챙겨가야겠네요. 그럼 명의변경하는데 얼마나 걸려요', '1시간 정도 소요될거에요.'],
 ['둘다 받고싶은데 하나로 합쳐서 받을 수 있어요', '네 가능합니다.'],
 ['금액은 얼마에요', '3 300원에 우편료 2 400원 추가돼요.'],
 ['직접 수령하러가도 돼요', '네. 문의주신 번호로 안내가 가면 수령하시러 방문하시면 돼요.'],
 ['어떤 방식이 있어요', '가상계좌로 입금하거나 수령하실때 현장결제도 가능해요.'],
 ['안녕하세요. 저 장학생 문의하려구요.', '네 말씀하세요.'],
 ['혹시 충남 한울타리 장학생이랑 희망드림 장학생이랑 중복 선발 가능한가요', '아니요. 중복선발은 배제하고있어요.'],
 ['장학생 신청기간이 어떻게 돼요', '신청기간은 9월 3일부터 24일까지 입니다.'],
 ['신청은 어떻게 해요', '신청방법은 충남인재육성재단에 개인정보 입력하시고 신청하시면 돼요.'],
 ['네. 그런데 제가 충남으로 전입기간이 1년 안되었는데 신청가능해요',
  '네 가능하세요. 접수 마감일까지 전입기간 1년미만인 대학생 대상으로 진행하고 있어요.'],
 ['마지막으로 질문 하나만 더 드릴게요. 장학금액은 얼마에요', '1인에 200만원이에요.'],

In [14]:
# 질문은 유지한채 답변을 다른 답변으로 변경하여 새로운 2차원 리스트 생성
neg_list = []
for q, a in answers_list:
    # q -> 질문
    # a -> 답변
    # 반복문에서 정상적인 답변을 제외한 나머지 답변의 리스트 생성
    cand = [ a2 for q2, a2 in answers_list if a2 != a]
    # 틀린 답변 하나를 선택
    neg_a = np.random.choice(cand)
    neg_list.append([q, neg_a] )

In [15]:
answers_list2 = [
    ['A', 'a'],
    ['B', 'b'],
    ['C', 'c'],
    ['D', 'd'],
    ['E', 'e']
]
neg_list2 = []
for q, a in answers_list2:
    # 1회차 반복 ->q('A'), a('a')
    # cand = [ a2 for q2, a2 in answers_list2 if a2 != a]
    cand = []
    for q2, a2 in answers_list2:
        if a2 != a:
            cand.append(a2)
    
    neg_a = np.random.choice(cand)
    neg_list2.append([q, neg_a] )

In [16]:
neg_list2

[['A', np.str_('e')],
 ['B', np.str_('a')],
 ['C', np.str_('d')],
 ['D', np.str_('a')],
 ['E', np.str_('d')]]

In [17]:
neg_df = pd.DataFrame(neg_list, columns = ['고객질문', '상담사답변'])
neg_df.head()

                 고객질문                            상담사답변
0  지방세를 내려면 어떻게 해야됩니까  네 원하시는 횟수 만큼 분할해서 납부하실 수도 있습니다.
1      은행을 직접방문해도 됩니까                         네 안녕하세요.
2     버스로 가는 방법도 있습니까   위택스라고 검색하셔서 자동차세 연납 신청하시면 됩니다.
3       다른 납부방법도 있습니까         400번 502번 버스를 이용하시면 됩니다.
4     사이트 주소가 어떻게 됩니까           방문접수 또는 우편접수로 받고 있습니다.

In [18]:
neg_df['label'] = 0

In [19]:
# df와 neg_df를 단순한 행 결합
dataset_df = pd.concat([df.head(1000), neg_df.head(1000)], axis=0, ignore_index=True)

In [20]:
dataset_df['label'].value_counts()

label
1    1000
0    1000
Name: count, dtype: int64

In [21]:
dataset_df

,index,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문,상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스,label
0,0.0,다산콜센터,일반행정 문의,B2240,고객,1.0,지방세납부,,Q,지방세를 내려면 어떻게 해야됩니까,,,이용하시는 은행의 사이트에서 지방세 납부가 가능합니다.,지방세,지방세/세금,"지방세,세금",1
1,6.0,다산콜센터,일반행정 문의,B2240,고객,7.0,지방세납부,,Q,은행을 직접방문해도 됩니까,,,방문납부도 가능합니다.,은행,은행/공공기관,"은행,공공기관",1
2,12.0,다산콜센터,일반행정 문의,B2240,고객,13.0,지방세납부,,Q,버스로 가는 방법도 있습니까,,,도보로 가시는게 빠를 것 같습니다.,버스,버스/교통수단,"버스,교통수단",1
3,14.0,다산콜센터,일반행정 문의,B2240,고객,15.0,지방세납부,,Q,다른 납부방법도 있습니까,,,위택스 사이트에서 납부하실수 있습니다.,,납부방법/지방세,,1
4,16.0,다산콜센터,일반행정 문의,B2240,고객,17.0,지방세납부,,Q,사이트 주소가 어떻게 됩니까,,,www.wetax.go.kr 입니다.,사이트,납부방법/지방세/ 위텍스/ 납부,"사이트,납부",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1시간권 말고 또 있나요,NaN,NaN,복사는 하드디스크에서 이동식USB를 복사하는 방법이 있다고 합니다.,NaN,NaN,NaN,0
1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,시간이 넘어가면 추가금액이 있어요,NaN,NaN,무고한 피해를 줄이기 위한 제도로 알고 있습니다.,NaN,NaN,NaN,0
1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,아 그것도 따로 있어요,NaN,NaN,네. 그렇습니다.,NaN,NaN,NaN,0
1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한시간권 30일 이용은 얼마인가요,NaN,NaN,네 가능합니다,NaN,NaN,NaN,0
1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,더 긴 정기권도 있나요,NaN,NaN,기본 대여시간 이내에 반납하는 것을 반복하면 연속적으로 자전거이용 가능합니다.,NaN,NaN,NaN,0

In [22]:
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [23]:
# train, test 셋으로 데이터프레임 분할
train_df, test_df = train_test_split(
    dataset_df, test_size=0.2, random_state=42, stratify=dataset_df['label']
)

In [24]:
train_df['label'].value_counts()

label
1    800
0    800
Name: count, dtype: int64

In [25]:
train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
test_ds = Dataset.from_pandas(test_df.reset_index(drop=True))
ds = DatasetDict(
    {
        'train' : train_ds, 
        'test' : test_ds
    }
)
ds

DatasetDict({
    train: Dataset({
        features: ['index', '도메인', '카테고리', '대화셋일련번호', '화자', '문장번호', '고객의도', '상담사의도', 'QA', '고객질문', '상담사질문(요청)', '고객답변', '상담사답변', '개체명 ', '용어사전', '지식베이스', 'label'],
        num_rows: 1600
    })
    test: Dataset({
        features: ['index', '도메인', '카테고리', '대화셋일련번호', '화자', '문장번호', '고객의도', '상담사의도', 'QA', '고객질문', '상담사질문(요청)', '고객답변', '상담사답변', '개체명 ', '용어사전', '지식베이스', 'label'],
        num_rows: 400
    })
})

In [26]:
import torch
from transformers import AutoTokenizer, DataCollatorWithPadding
# BertForSequenceClassification : BertModel -> <CLS> 토큰벡터 추출 -> dropout -> Linear까지 작업
from transformers import Trainer, TrainingArguments, BertForSequenceClassification
from sklearn.metrics import accuracy_score, f1_score

In [27]:
# 토큰화
MODEL_NAME = 'skt/kobert-base-v1'
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast = False)
max_len = 256       # 장문의 데이터인 경우에는 512까지 조절

def tok_fn(batch):
    # token화 할 데이터가 2개의 컬럼에 나눠져있다.
    enc = tokenizer(
        batch['고객질문'],
        batch['상담사답변'],
        truncation = True,
        max_length = max_len
    )
    # 일반적인 kobert 모델에서는 token_type_ids의 데이터 영역 필요 X
    enc.pop("token_type_ids", None) # 완전히 제거
    return enc

# remove_columns -> 특정 컬럼의 데이터를 제외 -> label컬럼을 제외한 나머지 모두
tok_ds = ds.map(tok_fn, batched = True,
                remove_columns=[col for col in dataset_df.columns if col not in ['label']],
                # 캐시 사용 안 함
                load_from_cache_file=False,
                desc = 'tokenizer clean'
                )

tokenizer clean: 100%|██████████| 1600/1600 [00:00<00:00, 16089.28 examples/s]
tokenizer clean: 100%|██████████| 400/400 [00:00<00:00, 17004.57 examples/s]

In [28]:
tok_ds

DatasetDict({
    train: Dataset({
        features: ['label', 'input_ids', 'attention_mask'],
        num_rows: 1600
    })
    test: Dataset({
        features: ['label', 'input_ids', 'attention_mask'],
        num_rows: 400
    })
})

In [29]:
# 배치마다 동적으로 padding토큰을 추가
collator = DataCollatorWithPadding(
    tokenizer = tokenizer
)

In [39]:
# BertModel -> CLS -> dropout -> linear
model = BertForSequenceClassification.from_pretrained(MODEL_NAME,
                                                      num_labels = 2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at skt/kobert-base-v1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [40]:
# 평가지표 함수
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis = -1)
    return {
        'accuracy_score' : accuracy_score(labels, preds),
        'f1_score' : f1_score(labels, preds)
    }

In [41]:
args = TrainingArguments(
    output_dir='./kobert_pair_cls',
    eval_strategy='epoch',
    save_strategy='epoch',
    logging_steps=50,
    learning_rate=5e-5,
    weight_decay=0.01,
    warmup_ratio=0.1,
    num_train_epochs=3,
    load_best_model_at_end=True,
    metric_for_best_model="f1_score",
    greater_is_better=True,
    report_to=[]
)

In [42]:
trainer = Trainer(
    model = model,
    args = args,
    train_dataset=tok_ds['train'],
    eval_dataset = tok_ds['test'],
    tokenizer = tokenizer,
    data_collator=collator,
    compute_metrics=compute_metrics
)

C:\Users\ekfla\AppData\Local\Temp\ipykernel_31720\2085847498.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [43]:
trainer.train()

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=600, training_loss=0.5305678049723307, metrics={'train_runtime': 328.6694, 'train_samples_per_second': 14.604, 'train_steps_per_second': 1.826, 'total_flos': 99250423414080.0, 'train_loss': 0.5305678049723307, 'epoch': 3.0})

In [44]:
# 평가
def score_pairs(question, answers):
    # 질문 1개 -> 답변 여러개 
    questions = [question] * len(answers)
    enc = tokenizer(
        questions,
        answers,
        return_tensors = 'pt',
        truncation = True,
        max_length = max_len,
        padding = True
    )
    # token_type_ids 제거
    enc.pop("token_type_ids", None)

    # 인코딩 데이터를 딕셔너리 형태로 변환
    inputs = {
        k : v for k, v in enc.items()
    }

    model.eval()
    with torch.no_grad():
        logits = model(**inputs).logits
        probs = torch.softmax( logits, dim = -1 )[:,1]  # label이 1일 확률
        # probs가 클수록 올바른 답변
    return probs.cpu().tolist()

In [45]:
question = '지방세 납부는 어디서 할수 있을까요?'
answers = [
    '이용하시는 은행 사이트나 앱에서 지방세 납부가 가능합니다',
    '지방층이 너무 두껍습니다',
    '동물 등록은 거주지 구청에서 처리하셔야 합니다.',
    '출입국 관련 업무는 외교부에서 담당합니다.'
]
scores = score_pairs(question, answers)

In [46]:
scores

[0.07260745018720627,
 0.08065266162157059,
 0.12948253750801086,
 0.134985089302063]

In [47]:
best_idx = int(np.argmax(scores))
for i, (a, s) in enumerate(zip(answers, scores)):
    # i -> 답변
    # a -> 답변
    # s -> 1의 적합 확률
    print(f"{i} {a} -> 적합확률 : {round(s, 3)}")
print(f'적합한 답변은 {best_idx} : {answers[best_idx]}')

0 이용하시는 은행 사이트나 앱에서 지방세 납부가 가능합니다 -> 적합확률 : 0.073
1 지방층이 너무 두껍습니다 -> 적합확률 : 0.081
2 동물 등록은 거주지 구청에서 처리하셔야 합니다. -> 적합확률 : 0.129
3 출입국 관련 업무는 외교부에서 담당합니다. -> 적합확률 : 0.135
적합한 답변은 3 : 출입국 관련 업무는 외교부에서 담당합니다.